config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get root to: 'welcome#index'
  get 'search_stock', to: 'stock#search'
  get 'search_friend', to: 'user#search'
  get 'user', to: 'user#index'
  get 'friend', to: 'user#show_friend'
  get 'friends_list', to: 'user#friends_list'
  get 'stock', to: 'stock#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'




end

app/models/stock.rb
class Stock < ApplicationRecord

    has_many :user_stocks
    has_many :users, through: :user_stocks

    validates :name, :ticker, presence: true



    def self.new_lookup(ticker_smbl)
        client = IEX::Api::Client.new(
            publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key],
            secret_token: Rails.application.credentials.iex_client[:secret_key],
            endpoint: 'https://sandbox.iexapis.com/v1'
        )
        begin
          new(ticker: ticker_smbl.upcase, name: client.company(ticker_smbl).company_name , last_price: client.price(ticker_smbl), news: client.news(ticker_smbl))
        rescue => exception
          return nil
        end
    end

    def self.check_db(ticker_smbl)
      find_by_ticker(ticker_smbl)
    end

    def get_update
      client = IEX::Api::Client.new(
          publishable_token: 'Tpk_ccfd5034761a48f48193c7a4f9876838',
          secret_token: 'Tsk_575ee15c9de048ba9952dfc31f78c7f9',
          endpoint: 'https://sandbox.iexapis.com/v1'
      )
      begin
        self.last_price = client.price(self.ticker)
        self.news = client.news(self.ticker)
        self.save
      rescue => exception
        return nil
      end
    end

end

app/models/user.rb
class User < ApplicationRecord

  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

   def has_stock(stock)
     user_stock= self.stocks.where(ticker: stock.ticker)
     !user_stock.empty?
   end

   def has_friend(friend)
      !Friendship.where(user: self).where(friend: friend).blank?
   end

end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

    def create
        friend = User.find_by_email(params[:email])
        if Friendship.where(user: current_user).where(friend: friend).blank?
          @friend= Friendship.create(user: current_user, friend: friend)
          flash[:notice] = "User "+ params[:email] + " was successfully marked as friend"
        else
          flash[:alert] = "You are already friends with" + params[:email]
        end
        redirect_back fallback_location: '/'
    end

    def destroy
      friendship = Friendship.find(params[:id])
      friendship.destroy
      flash[:alert] = friendship.friend.email + " was removed from you frindlist"
      redirect_back fallback_location: '/'
    end

end

app/controllers/stock_controller.rb
class StockController < ApplicationController


    def search
      if params[:stock].present?
        @stock = Stock.new_lookup(params[:stock])
        if @stock
          respond_to do |format|
            format.js { render partial: 'user/results'}
          end
        else
          respond_to do |format|
            flash.now[:alert] = "Please enter a valid symbol to search"
            format.js  { render partial: 'user/results'}
          end
        end
      else
        respond_to do |format|
          flash.now[:alert] = "Please enter a symbol to search"
          format.js  { render partial: 'user/results'}
        end
      end
    end

    def index
      @stock = Stock.find_by_ticker(params[:ticker])
      @stock.get_update
    end



end

app/controllers/user_controller.rb
class UserController < ApplicationController

    before_action :authenticate_user!

    def index
       @tracking_stock = current_user.stocks
    end

    def show_friend
      @user = User.find(params[:user])
      @tracking_stock = @user.stocks
      #redirect_to friend_path
    end

    def friends_list
      @friends_me = Friendship.where(friend_id: current_user)
      @friends_i = Friendship.where(user_id: current_user)
    end

    def search
      if params[:email].present?
        @user = User.where("email like ?", "%#{params[:email]}%")
        if !@user.empty?
          respond_to do |format|
            format.js { render partial: 'user/friend_results'}
          end
        else
          respond_to do |format|
            flash.now[:alert] = "Please enter a valid email to search"
            format.js  { render partial: 'user/friend_results'}
          end
        end
      else
        respond_to do |format|
          flash.now[:alert] = "Please enter a email to search"
          format.js  { render partial: 'user/friend_results'}
        end
      end
    end

end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController


    def create
        stock = Stock.check_db(params[:ticker])
        if stock.blank?
          stock = Stock.new_lookup(params[:ticker])
          stock.save
        end
        if UserStock.where(user: current_user).where(stock: stock).blank?
          @user_stock= UserStock.create(user: current_user, stock: stock)
          flash[:notice] = "Stock "+ stock.ticker + " was successfully added"
        else
          flash[:alert] = "You are already tracking " + stock.ticker
        end
        redirect_back fallback_location: '/'
    end

    def destroy
      stock = Stock.find(params[:id])
      user_stock = UserStock.where(user: current_user).where(stock: stock).first
      user_stock.destroy
      flash[:alert] = stock.ticker + " was removed from you portfolio"
      redirect_back fallback_location: '/'
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stock_helper.rb
module StockHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_messages.html.erb
<% if notice %>
  <div class = 'alert alert-success alert-dismissible fade show' role="alert">
    <button type = "button" class ="close" data-dismiss="alert" aria-label="Close" >
      <span aria-hidden="true">&times;</span>
    </button>
    <%= notice%>
  </div>
<% end %>


<% if alert %>
  <div class = 'alert alert-warning alert-dismissible fade show' role="alert">
    <button type = "button" class ="close" data-dismiss="alert" aria-label="Close" >
      <span aria-hidden="true">&times;</span>
    </button>
    <%= alert%>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
  <a class="navbar-brand" href="/"><b>FinTracker</b></a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item">
        <%= link_to 'Stocks',  user_path, class:"nav-link", method: :get %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Account
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if user_signed_in? %>
            <%= link_to 'Log Out',  destroy_user_session_path, class:"dropdown-item", method: :delete %>
            <!--- <%= link_to 'Edit',  '#', class:"dropdown-item disabled", method: :get %>
              -->
            <%= link_to 'Friends',  friends_list_path, class:"dropdown-item", method: :get %>
            <div class="dropdown-item disabled"><%=current_user.email%></div>
          <% else %>
            <%= link_to 'Log in',  new_user_session_path, class:"dropdown-item", method: :get %>
            <%= link_to 'Sign up',  new_user_registration_path, class:"dropdown-item", method: :get %>
          <% end %>
        </div>
      </li>
    </ul>
    <div style="margin-right: 10px;">
    </div>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
  <div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation'%>
    <div class="container">
      <%= render 'layouts/messages'%>
      <%= yield %>
    </div>
  </body>
</html>

app/views/stock/index.html.erb
<br>
<h3>Stock: <%=@stock.name%></h3>
<h4>Ticker: <%=@stock.ticker%></h4>
<h4>Last price: <%=@stock.last_price%></h4>
<br>
<h3>Last news:</h3>
<div id="accordion">
  <div class="card">
    <div class="card-header" id="headingOne">
      <h5 class="mb-0">
        <button class="btn btn-link" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          <%=@stock.news.first['headline']%>
        </button>
      </h5>
    </div>

    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordion">
      <div class="card-body">
        <%=@stock.news.first['summary']%>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" id="headingTwo">
      <h5 class="mb-0">
        <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          <%=@stock.news.second['headline']%>
        </button>
      </h5>
    </div>
    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
      <div class="card-body">
        <%=@stock.news.second['summary']%>
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" id="headingThree">
      <h5 class="mb-0">
        <button class="btn btn-link collapsed" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          <%=@stock.news.third['headline']%>
        </button>
      </h5>
    </div>
    <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
      <div class="card-body">
        <%=@stock.news.third['summary']%>

      </div>
    </div>
  </div>
</div>

app/views/user/_friend_results.html.erb
<div class="col-sm-10 no-left-padding no-right-padding">
<%= render 'layouts/messages'%>
</div>
<% if @user %>

    <div class="res col-sm-12 rb10" >
      <table class="table table-borderless " style="text-align: center; margin-bottom: 0px;">
          <% @user.each do |user|%>
          <% if user != current_user%>
          <tr>
            <td class="align-middle"><%=user.email%></td>

            <td class="align-middle">
              <% if user.has_friend(current_user) && current_user.has_friend(user) %>
              Mate
              <%else%>
              <% if current_user.has_friend(user)%>
              You are tracking him

              <%end%>
              <% if user.has_friend(current_user)%>
              He is tracking you

              <%end%>
              <%end%>

              </td>
             <td class="align-middle" style="width:160px">
              <div class="btn-group" role="group" aria-label="Basic example">
                <%= link_to friend_path(user: user), class:"btn btn-primary", type:'button',style:"width:42px", method: :get do%>
                  <%=fa_icon 'edit'%>
                <%end%>
                <%if !current_user.has_friend(user)%>
                  <%= link_to friendships_path(user: current_user, email: user.email), class:"btn btn-success", style:"width:42px", method: :post do %>
                  <%=fa_icon 'plus'%>
                  <%end%>
                <%else%>
                  <%= link_to friendship_path(user), class:"btn btn-danger", style:"width:42px", method: :delete do %>
                  <%=fa_icon 'trash'%>
                  <%end%>
                <%end%>


               </div>

            </td>
          </tr>
          <%end%>
          <%end%>
      </table>
    </div>
<%end%>

app/views/user/_friend_results.js.erb
document.querySelector('#friend_results').innerHTML = '<%= j render 'user/friend_results.html'%>'

app/views/user/_friend_track.html.erb
<div class="card col-sm-10" style="">
  <h5 class="card-title" style="margin-top:20px"><%= @user.email%>
    is tracking now:</h5>
  <div class="card-body">
    <table class="table table-hover " style="text-align: center;">
      <thead>
        <tr>
          <th scope="col">Ticker</th>
          <th scope="col">Company name</th>
          <th scope="col">Price</th>
          <%if current_user.has_friend(@user)%>
          <th scope="col" style="width:160px">Action</th>
          <%end%>
        </tr>
      </thead>
      <tbody>
        <% @tracking_stock.each do |stock| %>
          <tr>
            <td class="align-middle"><b><%=stock.ticker%></b></td>
            <td class="align-middle"><%=stock.name%></td>
            <td class="align-middle"><%=stock.last_price%></td>
            <td>
              <%if current_user.has_friend(@user)%>

              <!-- <div class="btn-group" role="group" aria-label="Basic example"> <button type="button" class="btn btn-primary">Details</button> -->

                <%if current_user.has_stock(stock)%>
                <div class="btn-group" role="group" aria-label="Basic example">
                  <%= link_to stock_path(ticker: stock.ticker), class:"btn btn-primary",style:"width:42px", type:'button', method: :get do %>
                    <%=fa_icon 'edit'%>
                  <%end%>


                   <%= link_to user_stock_path(stock), class:"btn btn-danger",style:"width:42px", type:'button', method: :delete do %>
                     <%=fa_icon 'trash'%>
                   <%end%>

                 </div>
                <%else%>
                <div class="btn-group" role="group" aria-label="Basic example">
                  <%= link_to stock_path(ticker: stock.ticker), class:"btn btn-primary", type:'button',style:"width:42px", method: :get do %>
                    <%=fa_icon 'edit'%>
                  <%end%>

                  <%= link_to user_stocks_path(user: current_user, ticker: stock.ticker), class:"btn btn-success", style:"width:42px", method: :post do %>
                    <%=fa_icon 'shopping-basket'%>
                  <%end%>
                <%end%>
                </div>

            <%end%>
            <!-- </div>-->


          </td>
        </tr>
      <%end%>
    </tbody>
  </table>
</div>
</div>

app/views/user/_results.html.erb
<div class="col-sm-10 no-left-padding no-right-padding">
<%= render 'layouts/messages'%>
</div>
<% if @stock %>
    <div class="card card-header res col-sm-10 rb10" >
      <table class="table table-borderless " style="text-align: center; margin-bottom: 0px;">
          <tr>
            <td class="align-middle"><b>Ticker:</b> <%=@stock.ticker%></td>
            <td class="align-middle"><b>Company name:</b> <%=@stock.name%></td>
            <td class="align-middle"><b>Price:</b> <%=@stock.last_price%></td>
            <td class="align-middle" style="width:160px">
              <div class="btn-group" role="group" aria-label="Basic example">
                <%= link_to stock_path(ticker: @stock.ticker), class:"btn btn-primary", type:'button',style:"width:42px", method: :get do %>
                  <%=fa_icon 'edit'%>
                <%end%>

                <%= link_to user_stocks_path(user: current_user, ticker: @stock.ticker), class:"btn btn-success", style:"width:42px", method: :post do %>
                <%=fa_icon 'shopping-basket'%>
                <%end%>

               </div>

            </td>
          </tr>
      </table>
    </div>
<%end%>

app/views/user/_results.js.erb
document.querySelector('#results').innerHTML = '<%= j render 'user/results.html'%>'

app/views/user/_track.html.erb
<div class="card col-sm-10" style="">
<h5 class="card-title" style="margin-top:20px">You are tracking now:</h5>
  <div class="card-body">
    <table class="table table-hover " style="text-align: center;">
    <thead>
        <tr>
        <th scope="col">Ticker</th>
        <th scope="col">Company name</th>
        <th scope="col">Price</th>
        <th scope="col" style="width:160px" >Action</th>
        </tr>
    </thead>
    <tbody>
    <% @tracking_stock.each do |stock| %>
        <tr>
        <td class="align-middle" ><b><%=stock.ticker%></b></td>
        <td class="align-middle"><%=stock.name%></td>
        <td class="align-middle"><%=stock.last_price%></td>
        <td>
           <div class="btn-group" role="group" aria-label="Basic example">
             <%= link_to stock_path(ticker: stock.ticker), class:"btn btn-primary",style:"width:42px", type:'button', method: :get do %>
               <%=fa_icon 'edit'%>
             <%end%>


              <%= link_to user_stock_path(stock), class:"btn btn-danger",style:"width:42px", type:'button', method: :delete do %>
                <%=fa_icon 'trash'%>
              <%end%>

            </div>
        </td>
        </tr>
        <%end%>
    </tbody>
    </table>
  </div>
</div>

app/views/user/friends_list.html.erb
<div class="card col-sm-10" style="">
  <h5 class="card-title" style="margin-top:20px">Your friends:</h5>
  <div class="card-body">
    <table class="table table-hover " style="text-align: center;">

      <tbody>

        <% if @friends_me%>
        <thead>
            <tr>
            <th scope="col">They track you</th>
            <th scope="col">Action</th>

            </tr>
        </thead>
          <% @friends_me.each do |friend| %>
            <tr>
              <td class="align-middle">
                <%= link_to friend_path(user: friend.user), method: :get do %>
                <%=friend.user.email%>
              <%end%>
            </td>
            <td>
              <%= link_to friendships_path(user: current_user, email: friend.user.email), class:"btn btn-success", style:"width:42px", method: :post do %>
              <%=fa_icon 'plus'%>
              <%end%>
              </td>
          </tr>
        <%end%>
      <%end%>
      <% if @friends_i%>
      <thead>
          <tr>
          <th scope="col">You track them</th>
          <th scope="col">Action</th>
          </tr>
      </thead>
        <% @friends_i.each do |friend| %>
          <tr>
            <td class="align-middle"><%= link_to friend_path(user: friend.friend), method: :get do %>
              <%=friend.friend.email%>
            <%end%>
          </td>
          <td class="align-middle">
            <%= link_to friendship_path(friend), class:"btn btn-danger",style:"width:42px", type:'button', method: :delete do %>
              <%=fa_icon 'trash'%>
            <%end%>
          </td>
        </tr>
      <%end%>
    <%end%>
  </tbody>
</table>

<div class='search-area'>
  <%= form_tag search_friend_path, remote: true, method: :get do %>
  <div class="form-group row">
    <div class="col-sm-11  no-right-padding">
      <%= text_field_tag :email, params[:email] , placeholder: 'User email....', autofocus: true, class: 'form-control form-control-lg', style: 'border-radius: 10px 0px 0px 10px;'%>
    </div>
    <div class="col-sm-1  no-left-padding ">
      <%= button_tag type: :submit, class: 'btn btn-success', style: 'height: 48px; width: 61.5px; border-radius: 0px 10px 10px 0px;' do%>
      <%=fa_icon 'search'%>
    <%end%>
  </div>
</div>
<%end%>

  <div id="friend_results" style="margin-top: 10px;margin-bottom: 10px;"></div>
</div>

app/views/user/index.html.erb
<div class="container" style='margin-left:60px;'>
<h3>Find stocks</h3>
<div class='search-area'>
  <%= form_tag search_stock_path, remote: true, method: :get do %>
  <div class="form-group row">
    <div class="col-sm-9  no-right-padding">
      <%= text_field_tag :stock, params[:stock] , placeholder: 'Stock ticker...', autofocus: true, class: 'form-control form-control-lg', style: 'border-radius: 10px 0px 0px 10px;'%>
    </div>
    <div class="col-sm-3  no-left-padding ">
      <%= button_tag type: :submit,  class: 'btn btn-success', style: 'height: 48px; width: 81.5px; border-radius: 0px 10px 10px 0px;' do%>
        <%=fa_icon 'search'%>
      <%end%>
    </div>
  </div>
  <%end%>

      <div id="results"  style="margin-top: 10px;margin-bottom: 10px;"></div>

      <%= render "user/track"%>
</div>
</div>

app/views/user/show_friend.html.erb
<div class="container" style='margin-left:60px;'>
<br>
      <%= render "user/friend_track"%>
</div>

app/views/welcome/index.html.erb
<br>
<div class="jumbotron jumbotron-fluid">
  <div class = "container" style="color: white;">
    <h1 class="display-4">Hello, world!</h1>
    <p class="lead" >This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
    <hr class="my-4">
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <% if !user_signed_in? %>
      <%= link_to 'Log in',  new_user_session_path, class:"btn btn-primary", method: :get %>
    <%end%>
  </div>
</div>